package com.alifew.alife.Utils;

import static com.unity3d.services.core.properties.ClientProperties.getApplicationContext;

import android.annotation.SuppressLint;
import android.content.ActivityNotFoundException;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.os.Build;
import android.os.Environment;
import android.text.Html;
import android.text.TextUtils;
import android.util.Log;
import android.view.View;
import android.widget.Toast;

import androidx.core.content.FileProvider;
import androidx.core.text.HtmlCompat;

import com.alifew.alife.BuildConfig;
import com.alifew.alife.R;
import com.gkemon.XMLtoPDF.PdfGenerator;
import com.gkemon.XMLtoPDF.PdfGeneratorListener;
import com.gkemon.XMLtoPDF.model.FailureResponse;
import com.gkemon.XMLtoPDF.model.SuccessResponse;
import com.google.zxing.BarcodeFormat;
import com.journeyapps.barcodescanner.BarcodeEncoder;

import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.Objects;

public class Helpers {

    public static String uniqueProductCodeGenerator(String text) {


        @SuppressLint("SimpleDateFormat") String timeStamp = new SimpleDateFormat("yyMMddHHmmss").format(Calendar.getInstance().getTime());

        if (text.length() > 0) {
            text = text.substring(0, 2).toLowerCase(Locale.ROOT) + "al";
            return text + timeStamp;
        } else {
            return timeStamp;
        }


    }

    public static Bitmap barCodeGenerator(Context context, String barCode) {
        //write code here
        Bitmap bitmap = null;
        try {
            BarcodeEncoder barcodeEncoder = new BarcodeEncoder();
            bitmap = barcodeEncoder.encodeBitmap(barCode, BarcodeFormat.CODE_128, 800, 400);


        } catch (Exception e) {

        }
        return bitmap;
    }

    public static void createPDF(View view, Context context, String fileName) {

        PdfGenerator.getBuilder()
                .setContext(context)
                .fromViewSource()
                .fromView(view)
                .setFileName(generateFileName(fileName))
                .setFolderName(Environment.DIRECTORY_DOCUMENTS)
                .openPDFafterGeneration(true)
                .build(new PdfGeneratorListener() {
                    @Override
                    public void onFailure(FailureResponse failureResponse) {
                        super.onFailure(failureResponse);
                        Log.d("dataxx", "onFailure: " + failureResponse.getErrorMessage());
                    }

                    @Override
                    public void showLog(String log) {
                        super.showLog(log);

                        Log.d("dataxx", "showLog: " + log);
                    }

                    @Override
                    public void onStartPDFGeneration() {
                        /*When PDF generation begins to start*/
                    }

                    @Override
                    public void onFinishPDFGeneration() {
                        /*When PDF generation is finished*/
                    }

                    @Override
                    public void onSuccess(SuccessResponse response) {
                        super.onSuccess(response);

                        Log.d("dataxx", "onSuccesPATH: " + response.getPath() + " ab: " + response.getFile().getAbsolutePath());
                        Toast.makeText(context, context.getResources().getString(R.string.file_save) + Html.fromHtml("\n<b>" + response.getPath() + "<b>"), Toast.LENGTH_SHORT).show();
//                        Intent myIntent = new Intent(Intent.ACTION_VIEW);
//                        myIntent.setDataAndType(FileProvider.getUriForFile(context, BuildConfig.APPLICATION_ID + ".provider", response.getFile()), "application/pdf");
//                        Intent j = Intent.createChooser(myIntent, "Choose an application to open with:");
//                        context.startActivity(j);


                    }
                });

//        PdfGenerator.getBuilder()
//                .setContext(context)
//                .fromViewSource()
//                .fromView(view)
//                .setFileName(generateFileName(fileName))
//                .setFolderName("ALIFE")
//                .openPDFafterGeneration(true)
//                .build(new PdfGeneratorListener() {
//                    @Override
//                    public void onFailure(FailureResponse failureResponse) {
//                        super.onFailure(failureResponse);
//                        Log.d("dataxx", "onFailure: " + failureResponse.getErrorMessage());
//                        /* If pdf is not generated by an error then you will findout the reason behind it
//                         * from this FailureResponse. */
//                        //Toast.makeText(MainActivity.this, "Failure : "+failureResponse.getErrorMessage(), Toast.LENGTH_SHORT).show();
//                        Toast.makeText(context, failureResponse.getErrorMessage(), Toast.LENGTH_SHORT).show();
//                    }
//
//                    @Override
//                    public void showLog(String log) {
//                        super.showLog(log);
//                        Log.d("dataxx", "log: " + log);
//                        /*It shows logs of events inside the pdf generation process*/
//                    }
//
//                    @Override
//                    public void onStartPDFGeneration() {
//
//                    }
//
//                    @Override
//                    public void onFinishPDFGeneration() {
//                        Log.d("dataxx", "Success: gen");
//                        savePDF(generateFileName(fileName), context);
//                    }
//
//                    @Override
//                    public void onSuccess(SuccessResponse response) {
//                        super.onSuccess(response);
//                        /* If PDF is generated successfully then you will find SuccessResponse
//                         * which holds the PdfDocument,File and path (where generated pdf is stored)*/
//                        //Toast.makeText(MainActivity.this, "Success", Toast.LENGTH_SHORT).show();
//                        Log.d("dataxx", "Success: " + response.getPath());
//
//
//
//                    }
//                });
    }

    private static void savePDF(String generateFileName, Context context) {

        String targetPDF;

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            //dir = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS) + "/" + FolderName);

            targetPDF = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS).toURI()) + "/" + generateFileName + ".pdf";
        } else {
            targetPDF = new File(Environment.getExternalStorageDirectory().toURI()) + "/" + generateFileName + ".pdf";

        }

        PdfDocument document = new PdfDocument();

        File file = new File(targetPDF);
        Log.d("dataxx", "savePDF: " + targetPDF);
        try {
            FileOutputStream fileOutputStream = new FileOutputStream(file);
            document.writeTo(fileOutputStream);
            Toast.makeText(context, "Successfully saved at " + targetPDF, Toast.LENGTH_SHORT).show();
            document.close();
            fileOutputStream.close();
            //openPDF(targetPDF, context);
        } catch (Exception e) {
            e.printStackTrace();
            Log.d("errorxx", e.getMessage());
            Toast.makeText(context, e.getMessage(), Toast.LENGTH_SHORT).show();

            //openPDF(targetPDF, context);
        }
    }

    @SuppressLint("SimpleDateFormat")
    private static String generateFileName(String fileName) {


        return fileName + new SimpleDateFormat("yyMMddHHmmss").format(Calendar.getInstance().getTime());
    }

    private static void openGeneratedPDF(String targetPdf, Context context) {

//        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
//            //dir = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS) + "/" + FolderName);
//
//            targetPDF = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS).toURI());
//        } else {
//            targetPDF = new File(Environment.getExternalStorageDirectory().toURI());
//
//        }
        String baseDir = Environment.getExternalStorageDirectory().getAbsolutePath();
        targetPdf = baseDir + targetPdf;

        Log.d("dataxx", "TARGET: " + targetPdf);

        try {
            File file = new File(targetPdf);
            if (file.exists()) {
                Uri path = FileProvider.getUriForFile(context, context.getPackageName() + ".xmlToPdf.provider", file);
                Intent intent = new Intent(Intent.ACTION_VIEW);
                intent.setDataAndType(path, "application/pdf");

                intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
                intent.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
                intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);

                try {
                    context.startActivity(intent);
                } catch (Exception e) {
                    //postFailure(e);
                    Log.d("dataxx", "OPENACTIVITYERROR: " + e.getMessage());
                }
            } else {
                //String path = TextUtils.isEmpty(directoryPath) ? "null" : directoryPath;
                Log.d("dataxx", "PDFOPENERROR: ELSE");
            }
        } catch (Exception exception) {
            Log.d("dataxx", "PDFOPENERROR: " + exception.getMessage());
        }

    }

    public static Bitmap loadBitmap(View v, int width, int height) {
        Bitmap bitmapPDF = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);

        Canvas canvas = new Canvas(bitmapPDF);
        v.draw(canvas);

        return bitmapPDF;
    }
}
